// <auto-generated />
using System;
using BoMForum.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoMForum.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20220403040732_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("BoMForum.Models.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommentText")
                        .HasColumnType("TEXT");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserPostID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CommentID");

                    b.HasIndex("UserPostID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BoMForum.Models.Tag", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TagID");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagID = 1,
                            TagText = "Atonement"
                        },
                        new
                        {
                            TagID = 2,
                            TagText = "Missionary Work"
                        },
                        new
                        {
                            TagID = 3,
                            TagText = "Godhead"
                        },
                        new
                        {
                            TagID = 4,
                            TagText = "Question"
                        },
                        new
                        {
                            TagID = 5,
                            TagText = "Testimony"
                        },
                        new
                        {
                            TagID = 6,
                            TagText = "Word of Wisdom"
                        },
                        new
                        {
                            TagID = 7,
                            TagText = "Law of Chastity"
                        },
                        new
                        {
                            TagID = 8,
                            TagText = "Tithing"
                        },
                        new
                        {
                            TagID = 9,
                            TagText = "Faith"
                        },
                        new
                        {
                            TagID = 10,
                            TagText = "Repentence"
                        },
                        new
                        {
                            TagID = 11,
                            TagText = "Baptism"
                        },
                        new
                        {
                            TagID = 12,
                            TagText = "Holy Ghost"
                        },
                        new
                        {
                            TagID = 13,
                            TagText = "Priesthood"
                        },
                        new
                        {
                            TagID = 14,
                            TagText = "Family"
                        },
                        new
                        {
                            TagID = 15,
                            TagText = "Covenants"
                        },
                        new
                        {
                            TagID = 16,
                            TagText = "Temples"
                        },
                        new
                        {
                            TagID = 17,
                            TagText = "Humility"
                        },
                        new
                        {
                            TagID = 18,
                            TagText = "Prophets"
                        },
                        new
                        {
                            TagID = 19,
                            TagText = "Hardships and Challenges"
                        },
                        new
                        {
                            TagID = 20,
                            TagText = "The Church"
                        });
                });

            modelBuilder.Entity("BoMForum.Models.UserPost", b =>
                {
                    b.Property<int>("UserPostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserPostText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPostTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserPostID");

                    b.ToTable("UserPosts");

                    b.HasData(
                        new
                        {
                            UserPostID = 1,
                            UserPostText = "Example Post",
                            UserPostTitle = "Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsum"
                        });
                });

            modelBuilder.Entity("BoMForum.Models.UserPostTag", b =>
                {
                    b.Property<int>("UserPostID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagID")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserPostID", "TagID");

                    b.HasIndex("TagID");

                    b.ToTable("UserPostTags");

                    b.HasData(
                        new
                        {
                            UserPostID = 1,
                            TagID = 1
                        });
                });

            modelBuilder.Entity("BoMForum.Models.Comment", b =>
                {
                    b.HasOne("BoMForum.Models.UserPost", "UserPost")
                        .WithMany()
                        .HasForeignKey("UserPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BoMForum.Models.UserPostTag", b =>
                {
                    b.HasOne("BoMForum.Models.UserPost", "UserPost")
                        .WithMany("UserPostTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoMForum.Models.Tag", "Tag")
                        .WithMany("UserPostTags")
                        .HasForeignKey("UserPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
